/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Opamp_1.h"
#include "Opamp_2.h"
#include "ADC_SAR.h"
#include "Pin_Sens_Low.h"
#include "Pin_Sens_Low_aliases.h"
#include "AMux_High.h"
#include "AMux_Low.h"
#include "Pin_Sens_High.h"
#include "Pin_Sens_High_aliases.h"
#include "IDAC.h"
#include "DieTemp.h"
#include "GPIO_VREF.h"
#include "GPIO_VREF_aliases.h"
#include "GPIO_S0.h"
#include "GPIO_S0_aliases.h"
#include "GPIO_S1.h"
#include "GPIO_S1_aliases.h"
#include "GPIO_EN.h"
#include "GPIO_EN_aliases.h"
#include "IDAC_IN.h"
#include "IDAC_IN_aliases.h"
#include "SPIS.h"
#include "SPIS_SPI_UART.h"
#include "SPIS_PINS.h"
#include "SPIS_SPI_UART_PVT.h"
#include "SPIS_PVT.h"
#include "SPIS_BOOT.h"
#include "Pin_TurnOn_Sink.h"
#include "Pin_TurnOn_Sink_aliases.h"
#include "ISR_TurnOn_Sink.h"
#include "Pin_TurnOff_Sink.h"
#include "Pin_TurnOff_Sink_aliases.h"
#include "ISR_TurnOff_Sink.h"
#include "ADC_SAR_IRQ.h"
#include "ADC_SAR_intClock.h"
#include "SPIS_SCBCLK.h"
#include "SPIS_ss_s.h"
#include "SPIS_ss_s_aliases.h"
#include "SPIS_miso_s.h"
#include "SPIS_miso_s_aliases.h"
#include "SPIS_SCB_IRQ.h"
#include "SPIS_sclk_s.h"
#include "SPIS_sclk_s_aliases.h"
#include "SPIS_mosi_s.h"
#include "SPIS_mosi_s_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

